### ISSUE TITLE
Problems with Solr 8.x database

### ISSUE THREAD

**Issue by Fikavec** [carrot2/carrot2#135] opened 2021-09-28 18:55 UTC
Hello! I'm found broken link in https://github.com/carrot2/carrot2#installation section to Apache Solr plugin (https://solr.apache.org/guide/8_9/result-clustering.html) lastest working links is https://solr.apache.org/guide/8_7/result-clustering.html
carrot2-4.3.1\dcs can't connect to Solr 8.x (tested on 8.1.1, 8.4.1 and 8.9.0) - cannot retrive information about collections:
![image](https://user-images.githubusercontent.com/83672821/135147502-ecaab362-dde2-4473-a260-f42189020f67.png)
Solr is availible and works (http://127.0.0.1:8984/solr/admin/cores?action=STATUS):
![image](https://user-images.githubusercontent.com/83672821/135146823-86471a2f-f3e6-4b7e-b85f-167de9c6fbc1.png)
Maybe Solr changed format of cores?action=STATUS ? 
Solr installation packages >8.7 cannot include the clustering contrib plugin with carrot2 in folder /contrib/ (for example, https://www.apache.org/dyn/closer.lua/lucene/solr/8.9.0/solr-8.9.0.zip)
Is Solr 8.9 and Solr 9 supported?
Thanks!

**Comment by dweiss** [comment] 2021-09-28 19:15
@stanislawosinski would have to take a look at the problem with the DCS - I was actually against adding Solr as a source because there are too many variables there to set it up reliably... 

As for the clustering plugin - the plugin has been removed from all of 8.x line because Carrot2 now requires Java 11 and Lucene/Solr is still on Java 8. The main branch still has the clustering plugin but I don't know when Solr 9.x will be released. There is a backported code for 8x but you'd have to rebase it and apply it against branch_8x manually:
https://issues.apache.org/jira/browse/SOLR-14974

**Comment by stanislawosinski** [comment] 2021-09-29 06:26
Just a quick check: is your Solr instance configured to serve CORS headers?

**Comment by Fikavec** [comment] 2021-09-29 19:15
@stanislawosinski thanks for your reply. Your's instruction works perfect - I'm adds to file solr\server\solr-webapp\webapp\WEB-INF\web.xml near 24 line (and restart Solr):
```xml
<filter>
   <filter-name>cross-origin</filter-name>
   <filter-class>org.eclipse.jetty.servlets.CrossOriginFilter</filter-class>
   <init-param>
     <param-name>allowedOrigins</param-name>
     <param-value>*</param-value>
   </init-param>
   <init-param>
     <param-name>allowedMethods</param-name>
     <param-value>GET,POST,OPTIONS,DELETE,PUT,HEAD</param-value>
   </init-param>
   <init-param>
     <param-name>allowedHeaders</param-name>
     <param-value>origin, content-type, accept</param-value>
   </init-param>
 </filter>

 <filter-mapping>
   <filter-name>cross-origin</filter-name>
   <url-pattern>/*</url-pattern>
 </filter-mapping>
```

But why DCS did not report about simple CORS problems in frontend UI and/or logs (I'm also read carrot2-4.3.1\dcs\logs\...)?
Maybe add this DCS CORS requirements and instruction into UI and/or DCS https://github.com/carrot2/carrot2#installation section? 
 Solr 9.x will work on java 11 and includes Carrot2 plugin?
@dweiss @stanislawosinski thank you very much!

**Comment by stanislawosinski** [comment] 2021-09-30 08:56
Excellent, I'm glad the solution worked!

> But why DCS did not report about simple CORS problems in frontend UI and/or logs (I'm also read carrot2-4.3.1\dcs\logs...)? 

There's no way for the DCS to know this, [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) authentication is governed entirely by the client making the request, the client does not report any errors to the server. Moreover, the browser does not report to the JavaScript initiating the request that the cause of failure is the missing CORS header, I have no idea why.

> Maybe add this DCS CORS requirements and instruction into UI and/or DCS https://github.com/carrot2/carrot2#installation section? 

Actually, both the UI and the documentation mention this :-)

![image](https://user-images.githubusercontent.com/628360/135420682-cd529086-f887-4e11-99a3-1e4ac2fb07f6.png)

![image](https://user-images.githubusercontent.com/628360/135420899-a812b074-14ff-4881-b57e-f0384b2cf077.png)


Solr 9.x will work on java 11 and includes Carrot2 plugin? @dweiss @stanislawosinski thank you very much!

**Comment by Fikavec** [comment] 2021-10-02 17:27
> Actually, both the UI and the documentation mention this :-)

@stanislawosinski i'm so sorry for this. Maybe I did not notice or understand this, because early disable CSP in jetty.xml and it was not written in the separate 2.0 section "Configure Solr database to serve CORS headers by instruction from [blog entry](https://opensourceconnections.com/blog/2015/03/26/going-cross-origin-with-solr/) and check this by instruction..." By default Solr don't serve CORS headers, some not advanced users (not DB admins, not web CORS specialists), like me, may not know this and not know how to check CORS. 

> Finally, the browser does not report to the JavaScript initiating the request that the cause of failure is the missing CORS header, I have no idea why.

From what is [written here](https://stackoverflow.com/a/19325710) by CORS specification browsers will not allow JS to see any response information when there is a CORS issue for security reasons. But I think that, Workbench, if error occured in the first interaction with Solr (or Elasticsearch) on retrive cores (index) list function by user click "connect" may output error message to user like "A network error occurred. This could be a CORS issue or a dropped internet connection. It is not possible for us to know. Please check сheck availability link [solr service url]/admin/cores?action=STATUS and Solr configuration to serve CORS headers by instruction..."

How about to add Solr cloud collections support?, because work with cores in cloud mode very uncomfortable. Solr cloud works with [collections](https://solr.apache.org/guide/8_9/collection-management.html#list). The list of collections can be received by the request [solr cloud url]/solr/admin/collections?action=LIST

Can I change documetns panel size for more comfortable reading (maybe by hide clustering options first column, or change in the second panel shows clusters into one column layout)?
![image](https://user-images.githubusercontent.com/83672821/135726016-282fe9fd-3598-4641-a388-4dccc422031d.png)

Can I see and change resulting workbentch query to Solr? Or add aditional to Query field Solr query parameters like fq (filter query list) or Raw Query Parameters (df, query parser type e.t.c.) like Solr Admin:
![image](https://user-images.githubusercontent.com/83672821/135726219-d9e41456-ce22-4a87-ada6-7104befcff00.png)

Thank you!

**Closed** 2021-10-02 17:29 UTC

**Comment by stanislawosinski** [comment] 2021-10-07 07:15
@Fikavec If you enable the advanced parameters, you'll see the "Additional search request parameters" for your extra Solr parameters.

![image](https://user-images.githubusercontent.com/628360/136336864-60163dd1-249d-411d-842e-404af9ca620e.png)
